spring:
  #  docker:
  #    compose:
  #      enabled: true
  #      file: compose-dev.yml
  #      start:
  #        command: up
  #      stop:
  #        command: down
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migrations/{vendor}/
    enabled: true
